import type { Vendor } from "../types/vendor";

export const vendors: Vendor[] = [
    {
        id: "1",
        companyName: "TechFlow Solutions",
        industry: "Technology",
        location: "San Francisco, CA",
        verificationStatus: "verified",
        dateAdded: "2021-01-01",
    },
    {
        id: "2",
        companyName: "Global Manufacturing Inc.",
        industry: "Manufacturing",
        location: "Detroit, MI",
        verificationStatus: "verified",
        dateAdded: "2021-01-01",
    },
    {
        id: "3",
        companyName: "Healthcare Partners LLC",
        industry: "Healthcare",
        location: "Boston, MA",
        verificationStatus: "pending",
        dateAdded: "2021-01-01",
    },
    {
        id: "4",
        companyName: "Finance First Group",
        industry: "Finance",
        location: "New York, NY",
        verificationStatus: "verified",
        dateAdded: "2021-01-01",
    },
    {
        id: "5",
        companyName: "Construction Pro Services",
        industry: "Construction",
        location: "Austin, TX",
        verificationStatus: "pending",
        dateAdded: "2021-01-01",
    },
    {
        id: "6",
        companyName: "Retail Excellence Corp",
        industry: "Retail",
        location: "Chicago, IL",
        verificationStatus: "verified",
        dateAdded: "2021-01-01",
    },
    {
        id: "7",
        companyName: "Energy Solutions Ltd",
        industry: "Energy",
        location: "Houston, TX",
        verificationStatus: "verified",
        dateAdded: "2021-01-01",
    },
    {
        id: "8",
        companyName: "Education Innovation Hub",
        industry: "Education",
        location: "Seattle, WA",
        verificationStatus: "pending",
        dateAdded: "2021-01-01",
    },
    {
        id: "9",
        companyName: "Food & Beverage Co",
        industry: "Food & Beverage",
        location: "Los Angeles, CA",
        verificationStatus: "verified",
        dateAdded: "2021-01-01",
    },
    {
        id: "10",
        companyName: "Transportation Logistics",
        industry: "Transportation",
        location: "Miami, FL",
        verificationStatus: "pending",
        dateAdded: "2021-01-01",
    },
    {
        id: "11",
        companyName: "Real Estate Dynamics",
        industry: "Real Estate",
        location: "Denver, CO",
        verificationStatus: "verified",
        dateAdded: "2021-01-01",
    },
    {
        id: "12",
        companyName: "Media & Entertainment Group",
        industry: "Media",
        location: "Atlanta, GA",
        verificationStatus: "verified",
        dateAdded: "2021-01-01",
    },
];
